name: Build

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Clean install dependencies
              run: npm ci

            - name: Check
              run: npm run check

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build
